admin.haircut/admin.haircut/Controllers/Base/BaseWebController.cs
using Admin.Haircut.Business.Authorization;
using Admin.Haircut.Business.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers.Base
{
    [ApiExceptionFilter]
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize]
    public class BaseWebController : Controller
    {
        public ApplicationEmployee CurrentEmployee
        {
            get
            {
                if (!HttpContext.User.Claims.Any())
                {
                    return new ApplicationEmployee();
                }

                var idClaim = HttpContext.User.Claims.FirstOrDefault(x => x.Type == AppClaimTypes.IdentityClaim);
                var fullnameClaim = HttpContext.User.Claims.FirstOrDefault(x => x.Type == AppClaimTypes.FullNameClaim);
                var usernameClaim = HttpContext.User.Claims.FirstOrDefault(x => x.Type == AppClaimTypes.UsernameClaim);

                if (idClaim == null)
                {
                    return new ApplicationEmployee();
                }

                return new ApplicationEmployee
                {
                    Id = int.Parse(idClaim.Value),
                    Fullname = fullnameClaim.Value,
                    Username = usernameClaim.Value
                };
            }
        }
    }
}

admin.haircut/admin.haircut/Controllers/Components/Base/BaseViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers.Components.Base
{
    public abstract class BaseViewComponent : ViewComponent
    {
    }
}

admin.haircut/admin.haircut/Controllers/Components/Shared/GenderOptionViewComponent.cs
using Admin.Haircut.Business.Core;
using Admin.Haircut.Controllers.Components.Base;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers.Components.Shared
{
    public class GenderOptionViewComponent : BaseViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(AppEnums.Gender gender)
        {
            return await Task.FromResult(View("~/Views/Shared/ViewComponents/_GenderOptionViewComponent.cshtml", gender));
        }
    }
}

admin.haircut/admin.haircut/Controllers/Components/Shared/PositionOptionViewComponent.cs
using Admin.Haircut.Business.Core;
using Admin.Haircut.Business.Service.Interfaces;
using Admin.Haircut.Controllers.Components.Base;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers.Components.Shared
{
    public class PositionOptionViewComponent : BaseViewComponent
    {
        private readonly IRuleService _ruleService;

        public PositionOptionViewComponent(IRuleService ruleService)
        {
            _ruleService = ruleService;
        }

        public async Task<IViewComponentResult> InvokeAsync(long id)
        {
            var ruleEmployee = await _ruleService.GetByIdEmployee(id);
            ViewBag.RuleEmployee = ruleEmployee;

            var model = await _ruleService.GetAll();
            return await Task.FromResult(View("~/Views/Shared/ViewComponents/_PositionOptionViewComponent.cshtml", model));
        }
    }
}

admin.haircut/admin.haircut/Controllers/DashboardController.cs
using Admin.Haircut.Business.Service.Interfaces;
using Admin.Haircut.Controllers.Base;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers
{
    [Route("/")]
    public class DashboardController : BaseWebController
    {
        private readonly IEmployeeService _employeeService;

        public DashboardController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        [Route("")]
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

admin.haircut/admin.haircut/Controllers/EmployeeController.cs
using Admin.Haircut.Business.Models.Base;
using Admin.Haircut.Business.Models.Employee;
using Admin.Haircut.Business.Service.Interfaces;
using Admin.Haircut.Controllers.Base;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers
{
    [Route("/employee")]
    public class EmployeeController : BaseWebController
    {
        private readonly IEmployeeService _employeeService;

        public EmployeeController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        [Route("")]
        public async Task<IActionResult> Index(
            [FromQuery(Name = "page")] string page = "1",
            [FromQuery(Name = "pageSize")] string pageSize = "")
        {
            var checkPage = long.TryParse(page, out long newPage);
            if (checkPage == false)
            {
                newPage = 1;
            };

            var checkPageSize = long.TryParse(pageSize, out long newPageSize);
            if (checkPageSize == false)
            {
                newPageSize = 100;
            };

            var request = new TableRequest
            {
                Page = newPage,
                PageSize = newPageSize
            };

            var model = await _employeeService.GetAll(request);
            return View(model);
        }

        [Route("add")]
        public async Task<IActionResult> Add()
        {
            return View();
        }

        [Route("{id}")]
        public async Task<IActionResult> Detail(long id)
        {
            var model = await _employeeService.Get(id);
            return View(model);
        }
    }
}

admin.haircut/admin.haircut/Controllers/LoginController.cs
using Admin.Haircut.Controllers.Base;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers
{
    [Route("/login")]
    public class LoginController : BaseWebController
    {
        [AllowAnonymous]
        [Route("")]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [Route("/logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
            return Redirect("/login");
        }
    }
}

admin.haircut/admin.haircut/Controllers/ProductController.cs
using Admin.Haircut.Business.Models.Base;
using Admin.Haircut.Business.Service.Interfaces;
using Admin.Haircut.Controllers.Base;
using Microsoft.AspNetCore.Mvc;

namespace Admin.Haircut.Controllers
{
    [Route("/product")]
    public class ProductController : BaseWebController
    {
        //private readonly IProductService _productService;

        //public ProductController(IProductService productService)
        //{
        //    _productService = productService;
        //}

        [Route("")]
        public async Task<IActionResult> Index(
            )
        {
            

            
            return View();
        }
    }
}

admin.haircut/admin.haircut/Views/Employee/Add.cshtml
@using Admin.Haircut.Business.Models.Base;
@using Admin.Haircut.Business.Models.Employee;
@using Admin.Haircut.Business.Core;


<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col-sm-6">
                    <h3>Tạo nhân viên</h3>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item">Users</li>
                        <li class="breadcrumb-item active">Edit Profile</li>
                    </ol>
                </div>
                <div class="col-sm-6">
                    <!-- Bookmark Start-->
                    <div class="bookmark">
                        <ul>
                            <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Tables"><i data-feather="inbox"></i></a></li>
                            <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Chat"><i data-feather="message-square"></i></a></li>
                            <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Icons"><i data-feather="command"></i></a></li>
                            <li><a href="javascript:void(0)" data-container="body" data-bs-toggle="popover" data-placement="top" title="" data-original-title="Learning"><i data-feather="layers"></i></a></li>
                            <li>
                                <a href="javascript:void(0)"><i class="bookmark-search" data-feather="star"></i></a>
                                <form class="form-inline search-form">
                                    <div class="form-group form-control-search">
                                        <input type="text" placeholder="Search..">
                                    </div>
                                </form>
                            </li>
                        </ul>
                    </div>
                    <!-- Bookmark Ends-->
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="edit-profile">
            <div class="row">
                <div class="col-xl-8">
                    <form class="card" id="modal_update_employee">
                        <div class="card-header pb-0">
                            <h4 class="card-title mb-0">Thông tin cá nhân</h4>
                            <div class="card-options"><a class="card-options-collapse" href="#" data-bs-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a><a class="card-options-remove" href="#" data-bs-toggle="card-remove"><i class="fe fe-x"></i></a></div>
                        </div>
                        <div class="card-body">
                          <div class="row">
                            <div class="col-md-6">
                              <div class="mb-3">
                                <label class="form-label">Họ tên</label>
                                <input class="form-control" type="text" placeholder="Họ tên" name="FullName">
                              </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                              <div class="mb-3">
                                <label class="form-label">Giới tính</label>
                                @await Component.InvokeAsync("GenderOption")
                              </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                              <div class="mb-3">
                                <label class="form-label">Ngày sinh</label>
                                <input class="form-control digits" type="date" value="" name="Birthday">
                              </div>
                            </div>
                            <div class="col-sm-12">
                              <div class="mb-3">
                                <label class="form-label">Địa chỉ</label>
                                <input class="form-control" type="text" placeholder="Địa chỉ" name="Address">
                              </div>
                            </div>
                            <div class="col-md-12">
                              <div class="mb-3">
                                <label class="form-label">Số điện thoại</label>
                                <input class="form-control" type="text" placeholder="Số điện thoại" name="Phone">
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="mb-3">
                                <label class="form-label">Vị trí</label>
                                @await Component.InvokeAsync("PositionOption")
                              </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                              <div class="mb-3">
                                <label class="form-label">Ngày bắt đầu</label>
                                <input class="form-control digits" type="date" value="" name="StartingDate">
                              </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                              <div class="mb-3">
                                <label class="form-label">Ngày kết thúc</label>
                                <input class="form-control digits" type="date" value="">
                              </div>
                            </div>
                            <div class="col-md-12">
                              <div class="mb-3">
                                <label class="form-label">Tên tài khoản</label>
                                <input class="form-control" type="text" placeholder="Tên tài khoản" name="Username">
                              </div>
                            </div>
                            <div class="col-md-12">
                              <div class="mb-3">
                                <label class="form-label">Mật khẩu</label>
                                <input class="form-control" type="password" placeholder="Mật khẩu" name="Password">
                              </div>
                            </div>                        
                            <div class="col-md-12">
                              <div>
                                <label class="form-label">Ghi chú</label>
                                <textarea class="form-control" rows="5" placeholder="Ghi chú" name="Note"></textarea>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card-footer text-end">
                            <button class="btn btn-primary" type="submit">Lưu</button>
                            <button class="btn btn-danger" type="reset">Hủy bỏ</button>
                        </div>
                    </form>
                </div>
                <div class="col-xl-4">
                    <div class="card">
                        <div class="card-header pb-0">
                            <h4 class="card-title mb-0">My Profile</h4>
                            <div class="card-options"><a class="card-options-collapse" href="#" data-bs-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a><a class="card-options-remove" href="#" data-bs-toggle="card-remove"><i class="fe fe-x"></i></a></div>
                        </div>
                        <div class="card-body">
                            <form>
                                <div class="row mb-2">
                                    <div class="profile-title">
                                        <div class="media">
                                            <img class="img-70 rounded-circle" alt="" src="../assets/images/user/7.jpg">
                                            <div class="media-body">
                                                <h3 class="mb-1 f-20 txt-primary">MARK JECNO</h3>
                                                <p class="f-12">DESIGNER</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <h6 class="form-label">Bio</h6>
                                    <textarea class="form-control" rows="5">On the other hand, we denounce with righteous indignation</textarea>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Email-Address</label>
                                    <input class="form-control" placeholder="your-email@domain.com">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Password</label>
                                    <input class="form-control" type="password" value="password">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Website</label>
                                    <input class="form-control" placeholder="http://Uplor .com">
                                </div>
                                <div class="form-footer">
                                    <button class="btn btn-primary btn-block">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Container-fluid Ends-->
</div>

@section Scripts
{
    <script src="~/assets/js/select2/select2.full.min.js"></script>
    <script>
        $(function() {

            $(".js-example-placeholder-multiple").select2({
                placeholder: "--Chọn vị trí--",
            });                      
        });
    </script>
}

@section Head{
    <link rel="stylesheet" type="text/css" href="~/assets/css/select2.css">
    <style>
        .select2-selection__rendered{
            padding-left: 5px !important;
            padding: 0.375rem 0.75rem
        }
        .select2-container--default {
            background-color: #fff;
            font-size: 14px;
            border-color: #e6edef;
            color: #717171;
        }
    </style>
}

admin.haircut/admin.haircut/Views/Shared/PartialViews/_FooterPartialViews.cshtml
<footer class="footer">
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-6 footer-copyright">
        <p class="mb-0">Copyright 2021-22 © viho All rights reserved.</p>
        </div>
        <div class="col-md-6">
        <p class="pull-right mb-0">Hand crafted & made with <i class="fa fa-heart font-secondary"></i></p>
        </div>
    </div>
    </div>
</footer>

admin.haircut/admin.haircut/Views/Shared/PartialViews/_HeaderPartialViews.cshtml
<div class="page-main-header">
    <div class="main-header-right row m-0">
        <div class="main-header-left">
            <div class="logo-wrapper"><a asp-controller="Employee" asp-action="Index"><img class="img-fluid" src="~/assets/images/logo/logo.png" alt=""></a></div>
            <div class="dark-logo-wrapper"><a href="index.html"><img class="img-fluid" src="~/assets/images/logo/dark-logo.png" alt=""></a></div>
            <div class="toggle-sidebar"><i class="status_toggle middle" data-feather="align-center" id="sidebar-toggle"></i></div>
        </div>
        <div class="left-menu-header col">
            <ul>
                <li>
                    <form class="form-inline search-form">
                        <div class="search-bg">
                            <i class="fa fa-search"></i>
                            <input class="form-control-plaintext" placeholder="Tìm kiếm.....">
                        </div>
                    </form><span class="d-sm-none mobile-search search-bg"><i class="fa fa-search"></i></span>
                </li>
            </ul>
        </div>
        <div class="nav-right col pull-right right-menu p-0">
            <ul class="nav-menus">
                <li><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i data-feather="maximize"></i></a></li>
                <li class="onhover-dropdown">
                    <div class="bookmark-box"><i data-feather="star"></i></div>
                    <div class="bookmark-dropdown onhover-show-div">
                        <div class="form-group mb-0">
                            <div class="input-group">
                                <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-search"></i></span></div>
                                <input class="form-control" type="text" placeholder="Search for bookmark...">
                            </div>
                        </div>
                        <ul class="m-t-5">
                            <li class="add-to-bookmark"><i class="bookmark-icon" data-feather="inbox"></i>Email<span class="pull-right"><i data-feather="star"></i></span></li>
                            <li class="add-to-bookmark"><i class="bookmark-icon" data-feather="message-square"></i>Chat<span class="pull-right"><i data-feather="star"></i></span></li>
                            <li class="add-to-bookmark"><i class="bookmark-icon" data-feather="command"></i>Feather Icon<span class="pull-right"><i data-feather="star"></i></span></li>
                            <li class="add-to-bookmark"><i class="bookmark-icon" data-feather="airplay"></i>Widgets<span class="pull-right"><i data-feather="star">   </i></span></li>
                        </ul>
                    </div>
                </li>
                <li class="onhover-dropdown">
                    <div class="notification-box"><i data-feather="bell"></i><span class="dot-animated"></span></div>
                    <ul class="notification-dropdown onhover-show-div">
                        <li>
                            <p class="f-w-700 mb-0">You have 3 Notifications<span class="pull-right badge badge-primary badge-pill">4</span></p>
                        </li>
                        <li class="noti-primary">
                            <div class="media">
                                <span class="notification-bg bg-light-primary"><i data-feather="activity"> </i></span>
                                <div class="media-body">
                                    <p>Delivery processing </p><span>10 minutes ago</span>
                                </div>
                            </div>
                        </li>
                        <li class="noti-secondary">
                            <div class="media">
                                <span class="notification-bg bg-light-secondary"><i data-feather="check-circle"> </i></span>
                                <div class="media-body">
                                    <p>Order Complete</p><span>1 hour ago</span>
                                </div>
                            </div>
                        </li>
                        <li class="noti-success">
                            <div class="media">
                                <span class="notification-bg bg-light-success"><i data-feather="file-text"> </i></span>
                                <div class="media-body">
                                    <p>Tickets Generated</p><span>3 hour ago</span>
                                </div>
                            </div>
                        </li>
                        <li class="noti-danger">
                            <div class="media">
                                <span class="notification-bg bg-light-danger"><i data-feather="user-check"> </i></span>
                                <div class="media-body">
                                    <p>Delivery Complete</p><span>6 hour ago</span>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li>
                    <div class="mode"><i class="fa fa-moon-o"></i></div>
                </li>
                <li class="onhover-dropdown">
                    <i data-feather="message-square"></i>
                    <ul class="chat-dropdown onhover-show-div">
                        <li>
                            <div class="media">
                                <img class="img-fluid rounded-circle me-3" src="~/assets/images/user/4.jpg" alt="">
                                <div class="media-body">
                                    <span>Ain Chavez</span>
                                    <p class="f-12 light-font">Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12">32 mins ago</p>
                            </div>
                        </li>
                        <li>
                            <div class="media">
                                <img class="img-fluid rounded-circle me-3" src="~/assets/images/user/1.jpg" alt="">
                                <div class="media-body">
                                    <span>Erica Hughes</span>
                                    <p class="f-12 light-font">Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12">58 mins ago</p>
                            </div>
                        </li>
                        <li>
                            <div class="media">
                                <img class="img-fluid rounded-circle me-3" src="~/assets/images/user/2.jpg" alt="">
                                <div class="media-body">
                                    <span>Kori Thomas</span>
                                    <p class="f-12 light-font">Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12">1 hr ago</p>
                            </div>
                        </li>
                        <li class="text-center"> <a class="f-w-700" href="javascript:void(0)">See All     </a></li>
                    </ul>
                </li>
                <li class="onhover-dropdown p-0">
                    <button class="btn btn-primary-light logout-button" type="button"><i data-feather="log-out"></i>Đăng xuất</button>
                </li>
            </ul>
        </div>
        <div class="d-lg-none mobile-toggle pull-right w-auto"><i data-feather="more-horizontal"></i></div>
    </div>
</div>

<script>
$(function() {
    $(".logout-button").on("click", function() {
        Swal.fire({
          title: 'Bạn có chắc chắn?',
          text: "",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Có, chắc chắn',
          cancelButtonText: 'Không'
        }).then((result) => {
          if (result.isConfirmed) {
              window.location.href = '@Url.Action("Logout", "Login")';
          }
        })
    })
})
</script>

admin.haircut/admin.haircut/Views/Shared/PartialViews/_LeftMenuPartialViews.cshtml
<header class="main-nav">
    <div class="sidebar-user text-center">
        <a class="setting-primary" href="javascript:void(0)"><i data-feather="settings"></i></a><img class="img-90 rounded-circle" src="../assets/images/dashboard/1.png" alt="">
        <div class="badge-bottom"><span class="badge badge-primary">New</span></div><a href="user-profile.html">
            <h6 class="mt-3 f-14 f-w-600">Emay Walter</h6>
        </a>
        <p class="mb-0 font-roboto">Human Resources Department</p>
        <ul>
            <li>
                <span><span class="counter">19.8</span>k</span>
                <p>Follow</p>
            </li>
            <li>
                <span>2 year</span>
                <p>Experince</p>
            </li>
            <li>
                <span><span class="counter">95.2</span>k</span>
                <p>Follower </p>
            </li>
        </ul>
    </div>
    <nav>
        <div class="main-navbar">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="mainnav">
                <ul class="nav-menu custom-scrollbar">
                    <li class="back-btn">
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="dropdown">
                        <a class="nav-link menu-title link-nav" asp-controller="Dashboard" asp-action="Index"><i data-feather="git-pull-request"></i><span>Dashboard</span></a>
                    </li>

                    <li class="sidebar-main-title">
                    <div>
                      <h6>QUẢN LÝ NHÂN VIÊN             </h6>
                    </div>
                  </li>
                  <li class="dropdown"><a class="nav-link menu-title" href="javascript:void(0)"><i data-feather="box"></i><span>Danh sách nhân viên</span></a>
                    <ul class="nav-submenu menu-content">
                      <li><a asp-controller="Employee" asp-action="Index">Nhân viên</a></li>
                      <li><a asp-controller="Employee" asp-action="Add">Tạo mới</a></li>
                    </ul>
                  </li>
                  <li class="dropdown"><a class="nav-link menu-title" href="javascript:void(0)"><i data-feather="box"></i><span>Quản lý sản phẩm</span></a>
                    <ul class="nav-submenu menu-content">
                      <li><a asp-controller="Product" asp-action="Index">Danh sách sản phẩm</a></li>
                      <li><a asp-controller="Product" asp-action="Add">Tạo mới</a></li>
                    </ul>
                  </li>
                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </div>
    </nav>
</header>

admin.haircut/admin.haircut/Views/Shared/ViewComponents/_GenderOptionViewComponent.cshtml
@using Admin.Haircut.Business.Core

<select class="form-control btn-square sex-option" name="Gender" required>
    @foreach (AppEnums.Gender item in (AppEnums.Gender[]) Enum.GetValues(typeof(AppEnums.Gender)))
    {
        if(item == Model)
        {
            <option value="@item" selected>
                @item.GetDescription()            
            </option>
        }
        else
        {
            <option value="@item">
                @item.GetDescription()
            </option>
        }
    }
</select>

admin.haircut/admin.haircut/Views/Shared/ViewComponents/_PositionOptionViewComponent.cshtml
@using Admin.Haircut.Business.Core
@using Admin.Haircut.Business.Models.Rule
@model List<RuleModel>;
@{
    var ruleEmployee = (List<RuleResponse>)ViewBag.RuleEmployee;
}

<select class="select2-rule-multiple col-sm-12" multiple="multiple" name="Rule" required>
    @foreach (var item in Model)
    {
        if(ruleEmployee.Any(x => x.IdRule == item.Id)){
            <option value="@item.Id" selected>@item.FullName</option>
        }else{
            <option value="@item.Id">@item.FullName</option>
        }
    }
</select>

<script>
    $(function() {
        $(".select2-rule-multiple").select2({
            placeholder: "--Chọn vị trí--",
        });
    })
</script>